## M·ªü ƒë·∫ßu

B√†i vi·∫øt n√†y s·∫Ω gi√∫p c√°c b·∫°n t√¨m ra b·ªÅ m·∫∑t tr√™n, d∆∞·ªõi ho·∫∑c c√°c m·∫∑t b√™n c·ªßa m·ªôt kh·ªëi Geometry t·ª´ m√¥ h√¨nh.Th∆∞·ªùng ƒë∆∞·ª£c s·ª≠ d·ª•ng trong r·∫•t nhi·ªÅu tr∆∞·ªùng h·ª£p nh∆∞ d·ª±ng h√¨nh, t·∫°o dim ƒë·ªëi t∆∞·ª£ng, t√≠nh di·ªán t√≠ch s√†n,ƒë·∫∑t m·ªôt ƒë·ªëi t∆∞·ª£ng l√™n b·ªÅ m·∫∑t,t√≠nh to√°n kh·ªëi l∆∞·ª£ng,...

## C√°ch x·ª≠ L√Ω
**Revit API**

Vi·ªác n√†y r·∫•t ƒë∆°n gi·∫£n, ·ª©ng v·ªõi m·ªói solid, b·∫°n s·∫Ω th·∫•y m·ªôt vector h∆∞·ªõng ra t·ª´ b·ªÅn m·∫∑t c·ªßa m·ªói m·∫∑t, nh∆∞ v·∫≠y vi·ªác c·ªßa b·∫°n ch·ªâ c·∫ßn ƒëi so s√°nh h∆∞·ªõng ƒë·ªÉ t√¨m ra m·∫∑t c·∫ßn l·∫•y.

```cs
public static PlanarFace GetTopFace(Solid solid)
        {
            PlanarFace topFace = null;
            FaceArray faces = solid.Faces;
            foreach (Face f in faces)
            {              
                PlanarFace pf = f as PlanarFace;
                if (pf.FaceNormal.IsAlmostEqualTo(new XYZ(0, 0, 1)))
                {
                    topFace = pf;
                }
            }
            return topFace;
        }
```

Tuy nhi√™n ta c√≤n c√≥ m·ªôt c√°ch ƒë∆∞·ª£c vi·∫øt s·∫µn b·∫±ng h√†m ·ªü ƒë√¢y, b·∫°n c√≥ th·ªÉ t√¨m hi·ªÉu th√™m

![](pic/_Image_289439a3-4075-49b2-b54b-7f4d21bd1b83.png)

**Dynamo**

1.Scripts ƒë∆°n gi·∫£n l·∫•y v·ªÅ Top Surface
![](pic/GetTopSurFace.png)

2.S·ª≠ d·ª•ng Codeblock tu·ª≥ ch·ªânh t·ª´ **Clockwork**
``` cs
almostzero=0.000000001;
ZNeg=Vector.ByCoordinates(0,0,-1);
vec = surf.NormalAtParameter(0.5,0.5);
z = vec.Z;
// Vertical
mask1 = z >= (0 - almostzero) && z <= (0 + almostzero);
DSCore.List.FilterByBoolMask(surf,mask1)["in"];
// Horizontal up
mask2 = vec.IsAlmostEqualTo(Vector.ZAxis());
DSCore.List.FilterByBoolMask(surf,mask2)["in"];
// Horizontal down
mask3 = vec.IsAlmostEqualTo(ZNeg);
DSCore.List.FilterByBoolMask(surf,mask3)["in"];
```
![](pic/GetTopSurFaceCodeBlock.png)

**DynamoAPI**

V√≠ d·ª• ƒë∆°n gi·∫£n l·∫•y v·ªÅ Top Surface

1.C#

```cs
public static List<Autodesk.DesignScript.Geometry.Surface> GetTop(Autodesk.DesignScript.Geometry.Geometry geometry)
        {
            List<Autodesk.DesignScript.Geometry.Surface> TopSurface = new List<Autodesk.DesignScript.Geometry.Surface>();
            Autodesk.DesignScript.Geometry.Geometry[] geometries = geometry.Explode();
            foreach (Autodesk.DesignScript.Geometry.Surface g in geometries)
            {
                double d = g.NormalAtParameter(0.5, 0.5).Z;
                if (d>0.1)
                {
                    TopSurface.Add(g);
                }
            }
            return TopSurface;
        }
```

2.Ngo√†i ra v·ªõi nh·ªØng b·ªÅ m·∫∑t h√¨nh h·ªçc ph·ª©c t·∫°p h∆°n ƒë√¥i khi g√¢y ra l·ªói v·ªõi b·ªÅ m·∫∑t kh√¥ng tr∆°n l√°n, m√¨nh c√≥ th·ªÉ s·ª≠ d·ª•ng th√™m ma thu·∫≠t t·ª´ t√°c gi·∫£ **Data-shapes**

![](pic/ca17b13e3fb67e4e327516fed4a452e11dac93ef.png)

```py
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import Surface as DSSurf
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import*
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
import sys
pyt_path = r'C:\\Program Files (x86)\\IronPython 2.7\\Lib'
sys.path.append(pyt_path)
import collections

def tolist(input):
	if isinstance(input,list):
		return UnwrapElement(input)
	else:
		return [UnwrapElement(input)]

def flatten(l):
    for el in l:
        if isinstance(el, collections.Iterable) and not isinstance(el, basestring):
            for sub in flatten(el):
                yield sub
        else:
            yield el

def tostring(x):
	return x.ToString()
def getgeomlist(x,opt):
	return list(x.get_Geometry(opt))
def getlength(c):
	return c.Length

def getfaces(x,opt):
	#getting geometryelements as list
	geomelems = getgeomlist(x,opt)
	#getting nested instance geometry for all geometry instances
	while any('GeometryInstance' in g for g in map(tostring,geomelems)):
		for index,i in enumerate(geomelems):
			if 'GeometryInstance' in i.ToString():
				geomelems[index] = i.GetInstanceGeometry()
			else:
				continue
	geomelems = list(flatten(geomelems))
	#getting all faces, keeping meshes
	faces = []
	for i in geomelems:
		if 'Solid' in i.ToString():
			faces.append(list(i.Faces))
		eli
```

## M·ªü r·ªông

N·∫øu b·∫°n ƒë√£ chai l√¨ v·ªõi nh·ªØng th·ª≠ th√°ch t·ª´ Geometry ƒë√≥ng tr√™n Dynamo, h√£y th·ª≠ t√¨m gi·∫£i ph√°p cho b√†i to√°n n√†y xem, bi·∫øt ƒë√¢u b·∫°n l·∫°i t√¨m ra √Ω t∆∞·ªüng ri√™ng cho m√¨nh üòÅ.
Xin c√°m ∆°n r·∫•t nhi·ªÅu t√°c gi·∫£ ƒë√£ gi√∫p m√¨nh ho√†n thi·ªán b√†i vi·∫øt t·ªïng k·∫øt n√†y.

## Tham kh·∫£o
<a href="https://forum.dynamobim.com/t/modified-floor-top-surface/16196/2" target="_blank">Dynamo Forum</a> 